development:
  sessions:
    default:
      database: loadmaster_logger_development
      hosts:
        - localhost:27017
      options:
  options:
    
test:
  sessions:
    default:
      database: loadmaster_logger_development
      hosts:
      options:
      consistency: :strong
 
production:
    sessions:
      default:
        database: loadmaster_logger_production
        hosts:
          - 195.231.85.192:27017
        options:
        consistency: :strong

# production:
#   host: 195.231.85.192
#   port: 27017
#   username: <%= ENV['MONGOID_USERNAME'] %>
#   password: <%= ENV['MONGOID_PASSWORD'] %>
#   database: loadmaster_logger_production
